### ISSUE TITLE
Add GA

### ISSUE THREAD

**Issue by yuto51942** [hello-slide/front#1]
Google Analyticsを追加する。

トークンは、`.env`で以下のように指定できるようにしてください。

```
GOOGLE_ANALYTICS_ID=XXXXXX
```

**Comment by Arisahyper** [comment]
追加しました

**Comment by yuto51942** [comment]
@Arisahyper えっと…PR出してくれますか？？？

**Comment by Arisahyper** [comment]
@yuto51942 
.envファイルって.gitignoreファイルで除外設定されてると思うんですけど、この場合ってどうすれば良いですか？

**Comment by yuto51942** [comment]
@Arisahyper 
それは、シークレットで定義するのでcommitしなくて大丈夫です。

**Comment by Arisahyper** [comment]
@yuto51942 

すみません、commitできる物がない状態でPRを出す、と言うのがいまいちよく分かっていません
もしかしたら自分が勘違いしてるかもなので確認なんですけど


- GAからテスト用のトラッキングIDを取得
- プロジェクト内に.envの作成
- .envにトークンとしてトラッキングIDを追加

上記の他にやる事ってありますか？ 
もしかして[こちらのサイト](https://panda-program.com/posts/nextjs-google-analytics)のようにGAをNext.jsのプロジェクト内で使えるようにするところまでを想定していますか？

**Comment by yuto51942** [comment]
すみません、説明不足でした。

このリポジトリ（next.js）でアクセス解析ができるように追加してください。
トークンは.envで定義してください。実際にデプロイする場合は環境変数は別で定義しますのでリポジトリ内には入れないようにお願いします。

**Comment by Arisahyper** [comment]
@yuto51942 
> すみません、説明不足でした。

そういう事でしたか！わかりました、大丈夫です

> このリポジトリ（next.js）でアクセス解析ができるように追加してください。

了解しました

> トークンは.envで定義してください。

了解しました

> 実際にデプロイする場合は環境変数は別で定義しますのでリポジトリ内には入れないようにお願いします。

今は特に意識しなくても大丈夫そうですかね
