### ISSUE TITLE
必要なページの作成

### ISSUE THREAD

**Issue by yuto51942** [hello-slide/front#4]
rootページの作成

以下のタスクごとにブランチを作成し、上から順番にPRを出してください。

- [x] #7
- [x] #16
- [ ] #8
- [x] #9
- [ ] #10
- [ ] #18 
- [ ] #19
- [ ] #21
- [x] #22 
- [ ] #23 
- [ ] #24
- [ ] #26

**Comment by Arisahyper** [comment]
ブランチを作った段階でPR出せば良いですか？

**Comment by yuto51942** [comment]
@Arisahyper 
このissueは私も作業するので私がブランチ切ります。

**Comment by Arisahyper** [comment]
@yuto51942 
了解です、早まってfooter用のブランチ切ってしまったので削除しておきます
